### PR TITLE
Added scripts to fetch+rebase and to status all underlaying git repos

### PR DESCRIPTION
**Pull request by lextiz**
Added scripts to "fetch"+"rebase" and to "status" all underlaying git repos

### CODE REVIEW

**Comment by skabashnyuk** [comment]
For which purposes you think this scripts will be useful.
Can you describe your flow?

**Comment by lextiz** [comment]
I think these scripts are useful for 2 purposes:
1) status: to have a picture of all the changes that were done to all Che projects (possibly by automated refactoring)
2) fetch+rebase: to update all the code automatically, without manually entering each folder

**Comment by skabashnyuk** [comment]
Can you describe how to use them (what they do, what issue may be) so we can add this information to README?

**Comment by lextiz** [comment]
The usage is as simple as running the script and looking at its output.

**Pull request merged**
